nvblox_config:
  container_name: 'nvblox_container'
  node_name: 'nvblox_node'
  remappings:
    - depth:
        image: '/oak/stereo/image_raw'
        info: '/oak/stereo/camera_info'
      color:
        image: '/camera0/camera0/segmentation/image_resized'
        info: '/camera0/camera0/segmentation/camera_info_resized'
      mask:
        image: '/camera0/segmentation/people_mask'
        info: '/camera0/camera0/segmentation/camera_info_resized'
  config_files:
    - package: 'isaac_ros_perceptor_bringup'
      path: 'params/default_nvblox_config.yaml'
  parameters:
    - use_lidar: false
    - input_qos: "SENSOR_DATA"
    - map_clearing_frame_id: "camera_link"
    - use_color: true
    - max_back_projection_distance: 7.0
    - static_mapper:
        esdf_slice_height: 0.0
        esdf_slice_min_height: 0.09
        esdf_slice_max_height: 0.65
    - dynamic_mapper:
        esdf_slice_height: 0.0
        esdf_slice_min_height: 0.09
        esdf_slice_max_height: 0.65

cuvslam_config:
  container_name: 'cuvslam_container'
  node_name: 'cuvslam_node'
  sync_matching_threshold_ms: 5.0
  enable_localization_n_mapping: false
  enable_imu_fusion: true
  rectified_images: true  
  remappings:
    stereo_images:
      - left:
          image: '/oak/left/image_raw'
          info: '/oak/left/camera_info'
          optical_frame: 'oak_left_camera_optical_frame'
        right:
          image: '/oak/right/image_raw'
          info: '/oak/right/camera_info'
          optical_frame: 'oak_right_camera_optical_frame'
    imu: '/oak/imu/data'
  config_files:
    - package: 'isaac_ros_perceptor_bringup'
      path: 'params/default_cuvslam_config.yaml'

common_config:
  map_frame: 'map'
  odom_frame: 'odom'
  robot_frame: 'oak-d-base-frame'

extra_topics:
  - '/tf_static'
